name: cell_sim
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - torchmetrics
  - torchdata
  - omegaconf
  - submitit
  - fvcore
  - iopath
  - pip
  - pip:
      - -r requirements.txt
